# Generated by Django 4.2.2 on 2023-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "short_url",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("hop_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
